### ISSUE TITLE
runtime issue

### ISSUE THREAD

**Issue by iwombat** [carsonmcdonald/AVSExample-Swift#1]
Hope this is the right place for questions.  If not, please direct me.

I have successfully built and set up security profiles.  When I hit
the configure button I get a browser page opening to the localhost:8777
port and see the login and logout.  When I press the LoginWAmazon
a new window opens and quickly closes and I get an error indicating
an auth issue:

http://localhost:8777/complete?error_description=lwa-invalid-parameter-bad-scope&error=invalid_scope

Is the window that opens supposed to remain for some input like
the client secret?  Did not see a description of what is supposed to
happen here.

I went back a couple times and verified that I generated key from iOSSettings,
have set bundle identifier correctly in config:

struct LoginWithAmazon {
        static let ClientId = "amzn1.application-oa2-client.6e860dbca30341c6bb0aef200bf4a039"
        static let ProductId = "AVSExample"
        static let DeviceSerialNumber = "1000-0000-0000-0000"
    }

and profiles on amazon side:

Security Profile Name   AVSExample
Security Profile Description    AVS Test
Security Profile ID amzn1.application.3960376499724df48ed0ad18a74dc081
Client ID   amzn1.application-oa2-client.6e860dbca30341c6bb0aef200bf4a039
Client Secret   f7af78579b0838e70e56c33dc0b75ef0eb141b1ab4dba7b58e5e056e5418249b

I tried localhost:8777 on both Netscape and Chrome browsers, just to make sure it was
not a browser issue.

Any ideas?

**Comment by carsonmcdonald** [comment]
@iwombat did you manage to get this working? It looks like you are trying on iOS maybe and that isn't something I managed to have time to test.

**Comment by iwombat** [comment]
Not yet.  I took a break to finish another part of the app.
I am running your example on my mac right now and I am still stuck at the same place.
One possibility: https://wombat.com works but https://www.wombat.com is not configured properly yet.Could it be trying to use www?
Did you use the Login with Amazon SDK:
http://login.amazon.com/ios#install_login_with_amazon_library

I just started looking at it...
-Frank

**Comment by thom-linden** [comment]
I was able to get Configure completed for Mac.  Did not realize I needed to add http://localhost:8777 to the Web Settings/Allowed Origins.  After that smooth flow to the Record button becoming active.

But, pressing Record I'm getting a quick 'Uploading recording' followed by 'Waiting for response' and then 'Upload error: Could not find boundry in AVS response.'.  It doesn't seem to try and capture spoken audio.

Suggestions?

Thx

**Comment by chintan1891** [comment]
@thom-linden  Did you found solution for "Upload error: Could not find boundry in AVS response."?

**Comment by thom-linden** [comment]
Yes, issue was around some of the UI coding.  Seemed to occur on some macs and not on others.  I have an updated zip I send you.  Let me know.

@carsonmcdonald would you like a copy?

**Comment by carsonmcdonald** [comment]
@thom-linden That would be great, or a PR if you have the time

**Comment by chintan1891** [comment]
@thom-linden Can you please send me a copy to "chintan1891@gmail.com"?

**Comment by thom-linden** [comment]
here's a zip.  Chintan tried out and worked.  Only ViewController changed (as I recall).  We've moved onto building a new app from scratch but this gave good basics on how to connect the dots.  Thanks much.

**Comment by premBlaze** [comment]
Thanks them-linden, code is working fine for Mac, can we convert the same code to iPhone/iPad, if the same code available with you, please share to "prem0423@gmail.com".
Thanks in advance.

**Comment by chintan1891** [comment]
Hi @premBlaze  Please check out this sample code (https://github.com/chintan1891/iOS-Alexa).
Please let me know if you face any issue in it.

**Comment by basheerMalaaAccolade** [comment]
@thom-linden the link you provided to the zip contains your client ID remove the link since it's expose risk to your product

**Comment by carsonmcdonald** [comment]
@basheerMalaaAccolade @thom-linden I have removed the link to the file but that ID probably should be changed.
